---
output:
  html_document:
    self_contained: false
---

```{r}
library(GCFPCA)
library(tidyverse)
library(lme4)
library(refund)
library(mvtnorm)
library(splines)
library(tf) #remotes::install_github("tidyfun/tf", ref = "dev")
library(tidyfun) # remotes::install_github("tidyfun/tidyfun")
library(patchwork)
library(sessioninfo)
theme_set(theme_minimal())

plot_pffr <- function(m) {
  layout(t(1:3))
  plot(m, select = 1,  scheme = 1) 
  lines(seq(0, 1, length.out = K), f_0(seq(0, 1, length.out = K)), col = 2)
  plot(m, select = 2, scheme = 1)
  lines(seq(0, 1, length.out = K), f_1(seq(0, 1, length.out = K)), col = 2)
  re <- matrix(predict(m, type = "terms")[[3]], ncol = K)
  tfd(re) |> plot(ylab = "REs")
}

plot_pffr_nhanes <- function(m) {
  layout(t(1:4))
  plot(m, select = 1, shift = m$coefficients[1], scheme = 1) #! shift by intercept -- CI will be too tight!
  plot(m, select = 2, scheme = 1, scale = 0)
  plot(m, select = 3, scheme = 1, scale = 0)
  re <- predict(m, type = "terms")[[4]]
  matrix(re, ncol = dim(re)[2]) |> tfd() |> plot(ylab = "REs", alpha = .1) #type = "lasagna")
}

plot_pffr_eta <- function(m, sim) {
  data <- tibble(
    true = sim$df_gcfpca |> select(id, index, eta) |> tfd(),
    pred = predict(m, type = "link") |> tfd(arg = tf_arg(true))
  ) |>
    pivot_longer(c(pred, true))
  ggplot(data) +
    geom_spaghetti(aes(y = value, col = name)) +
    facet_wrap(~name)
}

plot_gcfpca <- function(count_model) {
  plot_df <- cbind.data.frame(
    sind = rep(seq(0, 1, length.out = K), 2),
    betahat = c(data.matrix(count_model$betaHat)),
    betatrue = c(
      f_0(seq(0, 1, length.out = K)),
      f_1(seq(0, 1, length.out = K))
    ),
    X = c(
      rep("Intercept", K),
      rep("X", K)
    ),
    CI_L_pw = c(data.matrix(count_model$CI_L_pw)),
    CI_U_pw = c(data.matrix(count_model$CI_U_pw)),
    CI_L_joint = c(data.matrix(count_model$CI_L_joint)),
    CI_U_joint = c(data.matrix(count_model$CI_U_joint))
  ) %>%
    mutate(X = factor(X, levels = c(
      "Intercept",
      "X"
    )))

  plot_df %>%
    ggplot(aes(x = sind, y = betahat)) +
    geom_ribbon(aes(ymin = CI_L_joint, ymax = CI_U_joint, fill = "CI Joint"), alpha = 0.5) +
    geom_ribbon(aes(ymin = CI_L_pw, ymax = CI_U_pw, fill = "CI"), alpha = 0.5) +
    geom_line(aes(color = "GCFPCA")) +
    geom_line(aes(x = sind, y = betatrue, color = "truth")) +
    scale_fill_manual(values = c("CI" = "black", "CI Joint" = "lightgray"), name = "Confidence Interval") +
    scale_color_manual(values = c("GCFPCA" = "darkblue", "truth" = "red"), name = "Confidence Interval") +
    # Adding a horizontal dotted line at y = 0
    geom_hline(yintercept = 0, linetype = "dotted") +
    # Setting x-axis labels to show time
    scale_x_continuous(breaks = seq(0, 1, by = 0.2)) +
    # Facet the plot by variable X, with 3 columns
    facet_wrap(~X, ncol = 3, scales = "free_y") +
    # Adding axis labels and title
    labs(x = "Functional Domain", y = "", fill = "Confidence Interval")
}

plot_gcfpca_eta <- function(m, sim) {
  sim$df_gcfpca %>%
    mutate(eta_hat = as.vector(m$etas)) %>%
    pivot_longer(cols = c(eta, eta_hat)) |>
    # filter(id %in% c(1, 2, 8)) %>%
    ggplot(aes(x = index, y = value, group = id, col = name)) +
    geom_line() +
    facet_wrap(~ rev(name))
}
sessioninfo::session_info()

sessionInfo()$BLAS
sessionInfo()$LAPACK
```

## SIM

```{r pois_data}
# simulate data
library(splines)

I <- 100
K <- 500

# simulate data and save results
set.seed(1312)

# set true fixed effects
theta_0 <- rnorm(10 + 4, sd = 1) |> scale(scale = FALSE) #ensure mean 0 
theta_1 <- rnorm(10 + 4, sd = 1)

# set true fixed effects
f_0 <- function(s) bs(s, knots = seq(0.1, 0.9, len = 10), Boundary.knots = c(0, 1), intercept = TRUE) %*% theta_0
f_1 <- function(s) bs(s, knots = seq(0.1, 0.9, len = 10), Boundary.knots = c(0, 1), intercept = TRUE) %*% theta_1

count_sim <- gcfpca_simu(
  I = I, K = K, family = "poisson",
  beta0_true = f_0, beta1_true = f_1,
  fe_case = 2, re_case = 2
)
```

```{r pois_mod}
# use binwidth for 30 intervals to (roughly) compare with pffr model of similar
# coef-dimension using 25-40 basis functions:
gc_fpca_count_time <- system.time(
  count_model <- gc_fpca(
    formula = Y ~ X + (1 | id),
    data = count_sim$df_gcfpca,
    binwidth = K / 30,
    family = "poisson",
    #! if you supply *both* pve & npc you always get npc PCs from face
    pve = 0.95, npc = 4, periodicity = FALSE
  )
)
gc_fpca_count_time
``` 

```{r pois_pffr_re}
count_sim_pffr <- tf_nest(count_sim$df_gcfpca, Y, eta, .id = id, .arg = index)
count_sim_pffr$Y_mat <- as.matrix(count_sim_pffr$Y)

pffr_count_re_time <- system.time({
  pffr_count_re <- pffr(
    Y_mat ~ X + 
      s(id, bs = "re", bs.yindex = list(k = 10, bs = "cr")), # GC-FPCA uses 4 FPCs for this
    data = count_sim_pffr, family = "poisson",
    bs.int = list(k = 30, bs = "cr"), bs.yindex = list(k = 30, bs = "cr"),
    yind = tf_arg(count_sim_pffr$Y),
    algorithm = "bam", method = "fREML", discrete = TRUE
  )
})
pffr_count_re_time
``` 

```{r pois_pffr_pc}
pffr_count_pcre_time <- system.time({
  pffr_count_pilot <- pffr(Y_mat ~  X, 
    data = count_sim_pffr, family = "poisson",
    bs.int = list(k = 30, bs = "cr"), bs.yindex = list(k = 30, bs = "cr"),
    yind = tf_arg(count_sim_pffr$Y),
    algorithm = "bam", method = "fREML", discrete = TRUE
  )
  count_fpc_e <- resid(pffr_count_pilot) |>
    fpca.face(pve = .95, knots = 20, lower = 0) # as in gc_fpca
  count_efuns <- count_fpc_e$efunctions
  count_evalues <- count_fpc_e$evalues
  pffr_count_pcre <- pffr(
    Y_mat ~ X +
      pcre(
        id = id, efunctions = count_efuns,
        evalues = count_evalues, yind = tf_arg(count_sim_pffr$Y)
      ),
    data = count_sim_pffr, family = "poisson",
    bs.int = list(k = 30, bs = "cr"), bs.yindex = list(k = 30, bs = "cr"),
    yind = tf_arg(count_sim_pffr$Y),
    algorithm = "bam", method = "fREML", discrete = TRUE
  )
})
pffr_count_pcre_time

save.image(file = here::here("attic", "gfamm-checks-sim.RData"))

plot_gcfpca(count_model) /
  plot_gcfpca_eta(count_model, count_sim)

plot_pffr(pffr_count_re)
plot_pffr_eta(pffr_count_re, count_sim)

plot_pffr(pffr_count_pcre)
plot_pffr_eta(pffr_count_pcre, count_sim)
```

```{r, warning=FALSE}
## ----df_long-------------------------------------------------------------------------------------
df_long <- readRDS(here::here("data/df_long.rds")) 

## ----nhanes_gcfpca, warning=FALSE, message=FALSE-------------------------------------------------
gcfpca_start_t <- Sys.time()
nhanes_gcfpca <- gc_fpca(
  formula = mims ~ age + gender + (1 | id),
  data = df_long,
  binwidth = 30,
  family = "binomial",
  pve = 0.95, npc = 4, periodicity = TRUE
)
gcfpca_end_t <- Sys.time()
gcfpca_time_diff <- as.double(difftime(gcfpca_end_t, gcfpca_start_t, units = "mins"))
gcfpca_time_diff
```

```{r}
I <- length(unique(df_long$id))
K <- length(unique(df_long$index))

df_pffr <- data.frame(
  Y = I(matrix(df_long$mims, I, K, byrow = TRUE)),
  id = factor(unique(df_long$id)),
  age = df_long$age[!duplicated(df_long$id)],
  gender = df_long$gender[!duplicated(df_long$id)]
)

pffr_start_t <- Sys.time()
# changes:
# - k to 10/30 because overkill otherwise
# - basis to "cc" to mimic periodicity = TRUE
pffr_model_re <- pffr(Y ~ age + gender + s(id, bs = "re", bs.yindex = list(bs = "cc", k = 10)),
  algorithm = "bam", method = "fREML", discrete = TRUE,
  bs.yindex = list(bs = "cc", k = 30),
  bs.int = list(bs = "cc", k = 30),
  data = df_pffr,
  family = "binomial", yind = sort(unique(df_long$index))
)
pffr_end_t <- Sys.time()
pffr_re_time_diff <- as.double(difftime(pffr_end_t, pffr_start_t, units = "mins"))
pffr_re_time_diff

plot_pffr_nhanes(pffr_model_re)


pffr_start_t <- Sys.time()
pffr_model_pilot <- pffr(Y ~ age + gender,
  algorithm = "bam", method = "fREML", discrete = TRUE,
  bs.yindex = list(bs = "cc", k = 30),
  bs.int = list(bs = "cc", k = 30),
  data = df_pffr,
  family = "binomial", yind = sort(unique(df_long$index))
)
nhanes_fpc_e <- resid(pffr_model_pilot) |> fpca.face(npc = 4) # would need ~11 FPCs for 90% "PVE"
nhanes_efuns <- nhanes_fpc_e$efunctions
nhanes_evalues <- nhanes_fpc_e$evalues

system.time(pffr_model_pc <- pffr(
  Y ~ age + gender +
    pcre(
      id = id, efunctions = nhanes_efuns,
      evalues = nhanes_evalues, yind =sort(unique(df_long$index))
    ),
  algorithm = "bam", method = "fREML", discrete = TRUE,
  bs.yindex = list(bs = "cc", k = 30),
  bs.int = list(bs = "cc", k = 30),
  data = df_pffr,
  family = "binomial", yind = sort(unique(df_long$index))
))
pffr_end_t <- Sys.time()
(pffr_pc_time_diff <- as.double(difftime(pffr_end_t, pffr_start_t, units = "mins")))

save.image(file = here::here("attic", "gfamm-checks-full.RData"))

plot_pffr_nhanes(pffr_model_pc)

AIC(pffr_model_pc)
AIC(pffr_model_re)
AIC(nhanes_gcfpca$model)
```

```{r}
pffr_model <- pffr_model_re
sind = sort(unique(df_long$index))
df_pred <- data.frame("yindex.vec" = sind,
                      id = as.numeric(levels(df_long$id))[1],
                      id.vec = as.numeric(levels(df_long$id))[1],
                      age = 1, gender = 1)
betahat_pffr <- mgcv::predict.gam(pffr_model, newdata=df_pred, type='iterms', se.fit=TRUE)
CI_L_pffr <- betahat_pffr[[1]] - 1.96 * betahat_pffr[[2]]
CI_U_pffr <- betahat_pffr[[1]] + 1.96 * betahat_pffr[[2]]

#! shouldn't the intercept functions for pffr be shifted by the constant Intercept?

eta_pffr <- matrix(pffr_model$linear.predictors, nrow = length(unique(df_long$id)), 
                   ncol = length(unique(df_long$index)))


## ----plot_nhanes_fe, echo = TRUE, fig.show='hold'------------------------------------------------
plot_df <- cbind.data.frame(sind = rep(seq(0, 1, length.out = K), 3),
                            betahat = c(data.matrix(nhanes_gcfpca$betaHat)),
                            betahat_pffr = c(data.matrix(betahat_pffr[[1]][, -4])),
                            X = c(rep("Intercept", K),
                                  rep("Age", K),
                                  rep("Gender", K)),
                            CI_L_pw = c(data.matrix(nhanes_gcfpca$CI_L_pw)),
                            CI_U_pw = c(data.matrix(nhanes_gcfpca$CI_U_pw)),
                            CI_L_joint = c(data.matrix(nhanes_gcfpca$CI_L_joint)),
                            CI_U_joint = c(data.matrix(nhanes_gcfpca$CI_U_joint)),
                            CI_L_pffr = c(CI_L_pffr[, -4]),
                            CI_U_pffr = c(CI_U_pffr[, -4])) %>%
  mutate(X = factor(X, levels = c("Intercept",
                                  "Age",
                                  "Gender")))

plot_df %>%
  ggplot(aes(x = sind, y = betahat)) +
  #geom_ribbon(aes(ymin = CI_L_joint, ymax = CI_U_joint, fill = "CI Joint"), alpha = 0.5) +
  geom_ribbon(aes(ymin = CI_L_pw, ymax = CI_U_pw, fill = "CI"), alpha = 0.3) +
  geom_ribbon(aes(ymin = CI_L_pffr, ymax = CI_U_pffr, fill = "CI pffr"), alpha = 0.5) +
  geom_line(aes(color = "GCFPCA")) +
  geom_line(aes(x = sind, y = betahat_pffr, color = "pffr classic")) +
  scale_fill_manual(values = c("CI" = "blue", "CI Joint" = "lightblue", "CI pffr" = "pink"), name = "Confidence Interval") +
  scale_color_manual(values = c("GCFPCA" = "blue", "pffr classic" = "red"), name = "Confidence Interval") +
  # Adding a horizontal dotted line at y = 0
  geom_hline(yintercept = 0, linetype = "dotted") +
  # Setting x-axis labels to show time
  scale_x_continuous(breaks = seq(0, 1, by = 0.2)) +
  # Facet the plot by variable X, with 3 columns
  facet_wrap(~X, ncol = 3, scales = "free_y") +
  # Adding axis labels and title
  labs(x = "Functional Domain", y = "", fill = "Confidence Interval")


## ----plot_nhanes_eta-----------------------------------------------------------------------------
df_long %>%
  mutate(eta_hat = as.vector(nhanes_gcfpca$etas)) %>%
  mutate(eta_pffr = as.vector(eta_pffr)) %>%
  filter(id %in% c(63529, 67427, 82257)) %>%
  ggplot(aes(index, eta_pffr)) +
  geom_line() +
  geom_line(aes(y = eta_hat), linetype = 2, color = "salmon") +
  facet_wrap(~id)
``` 

```{r}
pffr_model <- pffr_model_pc
sind = sort(unique(df_long$index))
df_pred <- data.frame("yindex.vec" = sind,
                      id = as.numeric(levels(df_long$id))[1],
                      id.vec = as.numeric(levels(df_long$id))[1],
                      age = 1, gender = 1) |> 
  cbind(pffr_model_pc$pffr$pcreterms[[1]]$efunctions)
betahat_pffr <- mgcv::predict.gam(pffr_model, newdata=df_pred, type='iterms', se.fit=TRUE)
CI_L_pffr <- betahat_pffr[[1]] - 1.96 * betahat_pffr[[2]]
CI_U_pffr <- betahat_pffr[[1]] + 1.96 * betahat_pffr[[2]]

eta_pffr <- matrix(pffr_model_pc$linear.predictors, nrow = length(unique(df_long$id)), 
                   ncol = length(unique(df_long$index)))


## ----plot_nhanes_fe, echo = TRUE, fig.show='hold'------------------------------------------------
plot_df <- cbind.data.frame(sind = rep(seq(0, 1, length.out = K), 3),
                            betahat = c(data.matrix(nhanes_gcfpca$betaHat)),
                            betahat_pffr = c(data.matrix(betahat_pffr[[1]][, -4])),
                            X = c(rep("Intercept", K),
                                  rep("Age", K),
                                  rep("Gender", K)),
                            CI_L_pw = c(data.matrix(nhanes_gcfpca$CI_L_pw)),
                            CI_U_pw = c(data.matrix(nhanes_gcfpca$CI_U_pw)),
                            CI_L_joint = c(data.matrix(nhanes_gcfpca$CI_L_joint)),
                            CI_U_joint = c(data.matrix(nhanes_gcfpca$CI_U_joint)),
                            CI_L_pffr = c(CI_L_pffr[, -4]),
                            CI_U_pffr = c(CI_U_pffr[, -4])) %>%
  mutate(X = factor(X, levels = c("Intercept",
                                  "Age",
                                  "Gender")))

plot_df %>%
  ggplot(aes(x = sind, y = betahat)) +
  #geom_ribbon(aes(ymin = CI_L_joint, ymax = CI_U_joint, fill = "CI Joint"), alpha = 0.5) +
  geom_ribbon(aes(ymin = CI_L_pw, ymax = CI_U_pw, fill = "CI"), alpha = 0.3) +
  geom_ribbon(aes(ymin = CI_L_pffr, ymax = CI_U_pffr, fill = "CI pffr"), alpha = 0.5) +
  geom_line(aes(color = "GCFPCA")) +
  geom_line(aes(x = sind, y = betahat_pffr, color = "pffr PC")) +
  scale_fill_manual(values = c("CI" = "blue", "CI Joint" = "lightblue", "CI pffr" = "pink"), name = "Confidence Interval") +
  scale_color_manual(values = c("GCFPCA" = "blue", "pffr PC" = "red"), name = "Confidence Interval") +
  # Adding a horizontal dotted line at y = 0
  geom_hline(yintercept = 0, linetype = "dotted") +
  # Setting x-axis labels to show time
  scale_x_continuous(breaks = seq(0, 1, by = 0.2)) +
  # Facet the plot by variable X, with 3 columns
  facet_wrap(~X, ncol = 3, scales = "free_y") +
  # Adding axis labels and title
  labs(x = "Functional Domain", y = "", fill = "Confidence Interval")


## ----plot_nhanes_eta-----------------------------------------------------------------------------
df_long %>%
  mutate(eta_hat = as.vector(nhanes_gcfpca$etas)) %>%
  mutate(eta_pffr = as.vector(eta_pffr)) %>%
  filter(id %in% c(63529, 67427, 82257)) %>%
  ggplot(aes(index, eta_pffr)) +
  geom_line() +
  geom_line(aes(y = eta_hat), linetype = 2, color = "salmon") +
  facet_wrap(~id)
``` 


